In [1]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.0)
Requirement already satisfied: pillow>=8 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\akshata\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("Advertising.csv")

In [4]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
df.tail()

        TV  radio  newspaper  sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [6]:
print(df.columns)

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [7]:
df.tail(3)

        TV  radio  newspaper  sales
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [8]:
print(df.info)

<bound method DataFrame.info of         TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]>

In [9]:
print("Data Types of Each Column ")
print(df.dtypes)

Data Types of Each Column
TV           float64
radio        float64
newspaper    float64
sales        float64
dtype: object

In [10]:
print("Sum of Null (Missing) Values Per Column:")
null_counts = df.isnull().sum()
print(null_counts)

Sum of Null (Missing) Values Per Column:
TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [11]:
df_dropped = df.drop(columns=['radio'])
print(df_dropped.head(10))

      TV  newspaper  sales
0  230.1       69.2   22.1
1   44.5       45.1   10.4
2   17.2       69.3    9.3
3  151.5       58.5   18.5
4  180.8       58.4   12.9
5    8.7       75.0    7.2
6   57.5       23.5   11.8
7  120.2       11.6   13.2
8    8.6        1.0    4.8
9  199.8       21.2   10.6

In [12]:
df['updated_sales'] = df['sales'] * 1.10
print(df[['sales', 'updated_sales']].head())

   sales  updated_sales
0   22.1          24.31
1   10.4          11.44
2    9.3          10.23
3   18.5          20.35
4   12.9          14.19

In [13]:
print(df.shape)

(200, 5)

In [14]:
summury = df.describe()
max_values = df.max(numeric_only=True)
min_values = df.min(numeric_only=True)
mean_values = df.mean(numeric_only=True)
median_values = df.median(numeric_only=True)
std_div_values = df.std(numeric_only=True)

print(summury)

               TV       radio   newspaper       sales  updated_sales
count  200.000000  200.000000  200.000000  200.000000     200.000000
mean   147.042500   23.264000   30.554000   14.022500      15.424750
std     85.854236   14.846809   21.778621    5.217457       5.739202
min      0.700000    0.000000    0.300000    1.600000       1.760000
25%     74.375000    9.975000   12.750000   10.375000      11.412500
50%    149.750000   22.900000   25.750000   12.900000      14.190000
75%    218.825000   36.525000   45.100000   17.400000      19.140000
max    296.400000   49.600000  114.000000   27.000000      29.700000

In [15]:
print(df.describe)

<bound method NDFrame.describe of         TV  radio  newspaper  sales  updated_sales
0    230.1   37.8       69.2   22.1          24.31
1     44.5   39.3       45.1   10.4          11.44
2     17.2   45.9       69.3    9.3          10.23
3    151.5   41.3       58.5   18.5          20.35
4    180.8   10.8       58.4   12.9          14.19
..     ...    ...        ...    ...            ...
195   38.2    3.7       13.8    7.6           8.36
196   94.2    4.9        8.1    9.7          10.67
197  177.0    9.3        6.4   12.8          14.08
198  283.6   42.0       66.2   25.5          28.05
199  232.1    8.6        8.7   13.4          14.74

[200 rows x 5 columns]>

In [16]:
df=pd.read_csv("Salaries .csv")

In [17]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [18]:
df.head(10)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [19]:
df.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [20]:
df.tail(10)

         rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [21]:
print(df.columns)

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [22]:
print(df.shape)

(78, 6)

In [23]:
print(df.describe)

<bound method NDFrame.describe of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [24]:
print(df.info)

<bound method DataFrame.info of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [25]:
summury = df.describe()
max_values = df.max(numeric_only=True)
min_values = df.min(numeric_only=True)
mean_values = df.mean(numeric_only=True)
median_values = df.median(numeric_only=True)
std_div_values = df.std(numeric_only=True)
print(summury)

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [26]:
print("Sum of Null (Missing) Values Per Column:")
null_counts = df.isnull().sum()
print(null_counts)

Sum of Null (Missing) Values Per Column:
rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64

In [27]:
#drop all null values.
df.dropna()

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [28]:
print(" Starting Salary Analysis ---")

# a) Display records whose salary is greater than 50000.
print("a) \nRecords with Salary > 50000 ")
records_gt_50k = df[df['salary'] > 50000]
print(records_gt_50k)

# b) Display records whose salary is less than 20000.
print("b)\n Records with Salary < 20000")
records_lt_20k = df[df['salary'] < 20000]
print(records_lt_20k)

# c) Display records whose salary is between 20000 to 50000 .
print("\nc) Records with Salary between 20000 and 50000")
records_between_20_50k = df[df['salary'].between(20000, 50000)]
print(records_between_20_50k)

# d) Display records whose salary is greater than 100000.
print("\nd) Records with Salary > 100000")
records_gt_100k = df[df['salary'] > 100000]
print(records_gt_100k)

# e) Display records whose salary is less than 100000.
print("\n e) Records with Salary < 100000 ")
records_lt_100k = df[df['salary'] < 100000]
print(records_lt_100k)

 Starting Salary Analysis ---
a)
Records with Salary > 50000
         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]
b)
 Records with Salary < 20000
Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

c) Records with Salary between 20000 and 50000
Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

d) Records with Salary > 100000
         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
7        Prof          A   18       18    Male  126300
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
65       Prof          A   36       19  Female  117555
69       Prof          A   28        7  Female  116450
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

 e) Records with Salary < 100000
         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
6   AssocProf          A   20       17    Male   81285
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
12   AsstProf          B    1        0    Male   88000
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
38   AsstProf          B    4        3    Male   91000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
46   AsstProf          B   11        3  Female   74692
50   AsstProf          B   10        5  Female   97032
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
60   AsstProf          B    3        3  Female   92000
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065

In [29]:
#a) display records whose discipline is A.
print("a)records whose discipline is A")
dis_A = df[df['discipline'] == 'A']
print(dis_A)
#b) display records whose discipline is B.
print("\na)records whose discipline is B")
dis_B = df[df['discipline'] == 'B']
print(dis_B)
#c) display records whose service is greater than 10.
print("\na)records whose service is greater than 10")
service_gt_10 = df[df['service'] > 10]
print(service_gt_10)
#d) display records whose service is less than 5.
print("\na)records whose service is less than 5")
service_ls_5 = df[df['service'] < 5]
print(service_ls_5 )

a)records whose discipline is A
         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
32       Prof          A   27       19    Male  103275
37       Prof          A   20        8    Male  102000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

a)records whose discipline is B
         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
4        Prof          B   20       18    Male  104800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312

a)records whose service is greater than 10
         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
54  AssocProf          A   25       22  Female   62884
58       Prof          B   36       26  Female  144651
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
67       Prof          A   17       11  Female   90450
72       Prof          B   24       15  Female  161101
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

a)records whose service is less than 5
        rank discipline  phd  service     sex  salary
12  AsstProf          B    1        0    Male   88000
15      Prof          B   17        3    Male  150480
16  AsstProf          B    8        3    Male   75044
17  AsstProf          B    4        0    Male   92000
20  AsstProf          B    4        4    Male   92000
22  AsstProf          A    4        2    Male   73000
23  AsstProf          A    2        0    Male   85000
28  AsstProf          B    7        2    Male   91300
38  AsstProf          B    4        3    Male   91000
42  AsstProf          B    4        2  Female   80225
43  AsstProf          B    5        0  Female   77000
46  AsstProf          B   11        3  Female   74692
52      Prof          A   12        0  Female  105000
53  AsstProf          A    5        3  Female   73500
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
60  AsstProf          B    3        3  Female   92000
68  AsstProf          A    4        2  Female   77500
70  AsstProf          A    8        3  Female   78500

In [30]:
# a) display records of phd and salary.
print("\na) records of phd and salary.")
records_ps = df[['phd','salary']]
print(records_ps) 

# b) display records of rank, sex and salary.
print("\nb) records of rank, sex and salary.")
records_rss = df[['rank', 'sex' ,'salary']]
print(records_rss) 

# c) display records without salary.
print("\nc) records without salary.")
records_wo_sal = df.drop(columns=['salary'])
print(records_wo_sal) 

# d) display first 50 records with rank,service and salary.
print("\nd) first 50 records with rank,service and salary.")
records_rss_50 = df[['rank', 'service' ,'salary']].head(50)
print(records_rss_50) 

# e) display records whose rank is Prof.
print("\ne) records whose rank is Prof.")
records_rank_prof = df[df['rank'] == 'Prof']
print(records_rank_prof) 

# f) display records whose rank is AssocProf.
print("\nf) records whose rank is AssocProf")
records_rank_AssocProf = df[df['rank'] == 'AssocProf']
print(records_rank_AssocProf)

a) records of phd and salary.
    phd  salary
0    56  186960
1    12   93000
2    23  110515
3    40  131205
4    20  104800
..  ...     ...
73   18  105450
74   19  104542
75   17  124312
76   28  109954
77   23  109646

[78 rows x 2 columns]

b) records of rank, sex and salary.
         rank     sex  salary
0        Prof    Male  186960
1        Prof    Male   93000
2        Prof    Male  110515
3        Prof    Male  131205
4        Prof    Male  104800
..        ...     ...     ...
73       Prof  Female  105450
74  AssocProf  Female  104542
75       Prof  Female  124312
76       Prof  Female  109954
77       Prof  Female  109646

[78 rows x 3 columns]

c) records without salary.
         rank discipline  phd  service     sex
0        Prof          B   56       49    Male
1        Prof          A   12        6    Male
2        Prof          A   23       20    Male
3        Prof          A   40       31    Male
4        Prof          B   20       18    Male
..        ...        ...  ...      ...     ...
73       Prof          B   18       10  Female
74  AssocProf          B   19        6  Female
75       Prof          B   17       17  Female
76       Prof          A   28       14  Female
77       Prof          A   23       15  Female

[78 rows x 5 columns]

d) first 50 records with rank,service and salary.
         rank  service  salary
0        Prof       49  186960
1        Prof        6   93000
2        Prof       20  110515
3        Prof       31  131205
4        Prof       18  104800
5        Prof       20  122400
6   AssocProf       17   81285
7        Prof       18  126300
8        Prof       19   94350
9        Prof       51   57800
10       Prof       33  128250
11       Prof       23  134778
12   AsstProf        0   88000
13       Prof       33  162200
14       Prof       19  153750
15       Prof        3  150480
16   AsstProf        3   75044
17   AsstProf        0   92000
18       Prof        7  107300
19       Prof       27  150500
20   AsstProf        4   92000
21       Prof       30  103106
22   AsstProf        2   73000
23   AsstProf        0   85000
24       Prof       23   91100
25       Prof       31   99418
26       Prof       19  148750
27       Prof       43  155865
28   AsstProf        2   91300
29       Prof       20  123683
30  AssocProf        7  107008
31       Prof       21  155750
32       Prof       19  103275
33       Prof       18  120000
34  AssocProf        8  119800
35       Prof       23  126933
36       Prof       45  146856
37       Prof        8  102000
38   AsstProf        3   91000
39       Prof       18  129000
40       Prof       36  137000
41  AssocProf        8   74830
42   AsstProf        2   80225
43   AsstProf        0   77000
44       Prof       19  151768
45       Prof       25  140096
46   AsstProf        3   74692
47  AssocProf       11  103613
48       Prof       17  111512
49       Prof       18  122960

e) records whose rank is Prof.
    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   12        6    Male   93000
2   Prof          A   23       20    Male  110515
3   Prof          A   40       31    Male  131205
4   Prof          B   20       18    Male  104800
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
8   Prof          A   29       19    Male   94350
9   Prof          A   51       51    Male   57800
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
18  Prof          A   19        7    Male  107300
19  Prof          A   29       27    Male  150500
21  Prof          A   33       30    Male  103106
24  Prof          A   30       23    Male   91100
25  Prof          B   35       31    Male   99418
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
32  Prof          A   27       19    Male  103275
33  Prof          B   18       18    Male  120000
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
37  Prof          A   20        8    Male  102000
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
48  Prof          B   17       17  Female  111512
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
52  Prof          A   12        0  Female  105000
58  Prof          B   36       26  Female  144651
63  Prof          A   29       27  Female   91000
65  Prof          A   36       19  Female  117555
67  Prof          A   17       11  Female   90450
69  Prof          A   28        7  Female  116450
72  Prof          B   24       15  Female  161101
73  Prof          B   18       10  Female  105450
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646

f) records whose rank is AssocProf
         rank discipline  phd  service     sex  salary
6   AssocProf          A   20       17    Male   81285
30  AssocProf          B    9        7    Male  107008
34  AssocProf          B   12        8    Male  119800
41  AssocProf          A   13        8  Female   74830
47  AssocProf          B   11       11  Female  103613
54  AssocProf          A   25       22  Female   62884
56  AssocProf          A   10        8  Female   77500
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
64  AssocProf          A   26       24  Female   73300
71  AssocProf          B   12        9  Female   71065
74  AssocProf          B   19        6  Female  104542